apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  example.conf: |
    # Put custom nginx config here (example)
    # (You can mount this later if you want to test config override)

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  password: myStrongPass123
